OBJECTS_TYPES = ["watchtowers"]
LAYERS_WITH_TYPES = ["tiles", "traffic_signs"]
TILES = "tiles"
FRAMES = "frames"
FRAME = "frame"
TILE_MAPS = "tile_maps"
TILE_SIZE = "tile_size"
WATCHTOWERS = "watchtowers"
TRAFFIC_SIGNS = "traffic_signs"
GROUND_TAGS = "ground_tags"
VEHICLES = "vehicles"
CITIZENS = "citizens"
